server:
  port: 8080
  servlet:
    context-path: /music-platform

spring:
  application:
    name: MusicPlatform
  datasource:
    #    驱动地址
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    主协议:子协议://主机地址:端口号/数据库名称
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5

